Ask Richard if all the variables were created by the ICG gender or if the were detemined by the organisation. If they were created by default by the vendor, ask if there is a data dictionary manual.

Date: 14/02 - 21/02

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sales = pd.read_excel('two_weeks_sales.xls')

WARNING *** file size (39774881) not 512 + multiple of sector size (512)


In [3]:
sales.head()

Related Fields                               Unnamed: 1  \
0           Code                              Description   
1              1                  PRESCHOOL FISHERS PRICE   
2              3       NOVA NATURAL HOLD HAIR SPRAY 450ML   
3              6              KINDERGARTEN  FISHERS PRICE   
4             12  SMART CHEF 8'' PLASTIC STRAINER CH82255   

               Unnamed: 2     Unnamed: 3    Unnamed: 4  Unnamed: 5  \
0  Additional Description       Bar Code    Bar Code 2  Bar Code 3   
1                     NaN   030099499614  030099499621         NaN   
2                     NaN  5021156120683           NaN         NaN   
3                     NaN   030099499638  030099499645         NaN   
4                     NaN   676979822556           NaN         NaN   

        Unnamed: 6       Unnamed: 7  Unnamed: 8         Unnamed: 9  ...  \
0  Serial Number 2  Serial Number 3  Department            Section  ...   
1     030099499621              NaN    BOOKSHOP              BOOKS  ...   
2              NaN              NaN  TOILETRIES      PERSONAL CARE  ...   
3     030099499645              NaN    BOOKSHOP              BOOKS  ...   
4              NaN              NaN   HOUSEHOLD  KITCHEN & DINNING  ...   

  Sales: (15/02/2021,28/02/2021) Unnamed: 63 Unnamed: 64 Unnamed: 65  \
0                            Qty      AMOUNT        Cost       % M/S   
1                              0           0           0           0   
2                              3        4320        3000     30.5556   
3                              0           0           0           0   
4                              0           0           0           0   

  Unnamed: 66 Unnamed: 67    Unnamed: 68   Unnamed: 69 Unnamed: 70 Unnamed: 71  
0       % M/C      Profit  Documents Num  Num. Clients      Weight   UdMedida2  
1           0           0              0             0           0           0  
2          44        1320              3             2           0           0  
3           0           0              0             0           0           0  
4           0           0              0             0           0           0  

[5 rows x 72 columns]

In [4]:
sales.sample(7)

Related Fields                                Unnamed: 1 Unnamed: 2  \
16955          55554                          TOY A330 AIRLINE        NaN   
19660          59094         TOY DOLL YONG BABY SHOP CXY555032        NaN   
10700          45782  KIRKLANDSIGN ORGANIC SOYMILK VANILL 946M        NaN   
14878          52599           FLAVIA PERFUME SPRAY MEN  200ML        NaN   
7922           39388            ORAL CARE KIT SPRING FRESH B/S        NaN   
12499          48966          KARIS NATURAL ORANGE LOTION 400M        NaN   
9807           44113            THE TRADER'S DREAM ANNA JACOBS        NaN   

          Unnamed: 3 Unnamed: 4  Unnamed: 5 Unnamed: 6  Unnamed: 7  \
16955        5002553        NaN  9995002553        NaN  9995002553   
19660  5262121002072        NaN         NaN        NaN         NaN   
10700   096619998616        NaN         NaN        NaN         NaN   
14878  6294015105971        NaN         NaN        NaN         NaN   
7922   6291103079893        NaN         NaN        NaN         NaN   
12499  8904035418316        NaN         NaN        NaN         NaN   
9807   9781444711325        NaN         NaN        NaN         NaN   

                     Unnamed: 8        Unnamed: 9  ...  \
16955                      TOYS         PLAY TOYS  ...   
19660                      TOYS         PLAY TOYS  ...   
10700                   GROCERY            DRINKS  ...   
14878  HEALTH & BEAUTY PRODUCTS  DEODRANT/ROLL ON  ...   
7922                 TOILETRIES     PERSONAL CARE  ...   
12499                TOILETRIES     PERSONAL CARE  ...   
9807                   BOOKSHOP             BOOKS  ...   

      Sales: (15/02/2021,28/02/2021) Unnamed: 63 Unnamed: 64 Unnamed: 65  \
16955                              0           0           0           0   
19660                              0           0           0           0   
10700                             27     40587.5       26625      34.401   
14878                              0           0           0           0   
7922                               0           0           0           0   
12499                              5      6050.7     3541.67     41.4668   
9807                               0           0           0           0   

      Unnamed: 66 Unnamed: 67 Unnamed: 68 Unnamed: 69 Unnamed: 70 Unnamed: 71  
16955           0           0           0           0           0           0  
19660           0           0           0           0           0           0  
10700     52.4413     13962.5          23           6           0           0  
14878           0           0           0           0           0           0  
7922            0           0           0           0           0           0  
12499     70.8433     2509.03           6           2           0           0  
9807            0           0           0           0           0           0  

[7 rows x 72 columns]

In [5]:
sales.columns = ['Code', 'Description', 'Additional Description', 'Bar Code',
       'Bar Code 2', 'Bar Code 3', 'Serial Number 2', 'Serial Number 3',
       'Department', 'Section', 'Family', 'SubFamily', 'Brand', 'Line',
       'Reference', 'Propiedad 1', 'Propiedad 2', 'Propiedad 3', 'Measure',
       'UP1', 'UP2', 'UP3', 'UP4', 'UT ', 'US1', 'US2', 'US3', 'US4', 'SC?',
       'Weight?', 'NumSeries?', 'It has Serial Numbers', 'Item Type', 'Unlist',
       'Kit items', 'Date LP', 'Price LP', 'Price', '%Disc LP',
       'Last header discount', 'Last cost', 'Average Cost', 'Stock cost',
       'Manufacturing', 'Date LS', 'Date Modif', 'Type', 'Purchase Tax',
       'Sale Tax', 'Purchase Acco.Entry', 'Sale Acco. Entry',
       'Purchase Warranty', 'Sale Warranty', 'Currency Code', 'Currency',
       'Picture', 'Season', 'Weight', 'Format', 'Measure 2', 'Charge 1',
       'Charge 2', 'Qty', 'AMOUNT', 'Cost', '% M/S', '% M/C', 'Profit',
       'Documents Num', 'Num. Clients', 'Weight', 'UdMedida2']

In [6]:
sales.drop([0], axis = 0, inplace = True) 

In [7]:
sales.head()

Code                              Description Additional Description  \
1    1                  PRESCHOOL FISHERS PRICE                    NaN   
2    3       NOVA NATURAL HOLD HAIR SPRAY 450ML                    NaN   
3    6              KINDERGARTEN  FISHERS PRICE                    NaN   
4   12  SMART CHEF 8'' PLASTIC STRAINER CH82255                    NaN   
5   21                  COLOURING BOOK LETTERS                     NaN   

        Bar Code    Bar Code 2 Bar Code 3 Serial Number 2 Serial Number 3  \
1   030099499614  030099499621        NaN    030099499621             NaN   
2  5021156120683           NaN        NaN             NaN             NaN   
3   030099499638  030099499645        NaN    030099499645             NaN   
4   676979822556           NaN        NaN             NaN             NaN   
5   088908152014           NaN        NaN             NaN             NaN   

   Department            Section  ... Qty AMOUNT  Cost    % M/S % M/C Profit  \
1    BOOKSHOP              BOOKS  ...   0      0     0        0     0      0   
2  TOILETRIES      PERSONAL CARE  ...   3   4320  3000  30.5556    44   1320   
3    BOOKSHOP              BOOKS  ...   0      0     0        0     0      0   
4   HOUSEHOLD  KITCHEN & DINNING  ...   0      0     0        0     0      0   
5    BOOKSHOP              BOOKS  ...   0      0     0        0     0      0   

  Documents Num Num. Clients Weight UdMedida2  
1             0            0      0         0  
2             3            2      0         0  
3             0            0      0         0  
4             0            0      0         0  
5             0            0      0         0  

[5 rows x 72 columns]

In [8]:
sales.shape

(27178, 72)

In [9]:
sales.describe()

Code       Description Additional Description       Bar Code  \
count   27177             27174                      2          27173   
unique  27177             27065                      2          27173   
top     65535  DELIVERY CHARGES            MIXED PASTA  7399687147119   
freq        1                 6                      1              1   

           Bar Code 2  Bar Code 3 Serial Number 2 Serial Number 3 Department  \
count            1492        6414            1492            6414      27170   
unique           1492        6383            1492            6383         13   
top     8718951182820  9999920020   8718951182820      9999920020  HOUSEHOLD   
freq                1           2               1               2       5715   

              Section  ...      Qty   AMOUNT     Cost    % M/S    % M/C  \
count           27034  ...  27177.0  27178.0  27178.0  27178.0  27178.0   
unique            108  ...    592.0   6028.0   4889.0   7703.0   7692.0   
top     PERSONAL CARE  ...      0.0      0.0      0.0      0.0      0.0   
freq             3320  ...  18055.0  18065.0  18095.0  18210.0  18240.0   

         Profit Documents Num Num. Clients Weight  UdMedida2  
count   27178.0         27177        27177  27177      27177  
unique   7584.0           387          126      1          1  
top         0.0             0            0      0          0  
freq    18204.0         17924        17924  27177      27177  

[4 rows x 72 columns]

In [10]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27178 entries, 1 to 27178
Data columns (total 72 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Code                    27177 non-null  object
 1   Description             27174 non-null  object
 2   Additional Description  2 non-null      object
 3   Bar Code                27173 non-null  object
 4   Bar Code 2              1492 non-null   object
 5   Bar Code 3              6414 non-null   object
 6   Serial Number 2         1492 non-null   object
 7   Serial Number 3         6414 non-null   object
 8   Department              27170 non-null  object
 9   Section                 27034 non-null  object
 10  Family                  14939 non-null  object
 11  SubFamily               8588 non-null   object
 12  Brand                   80 non-null     object
 13  Line                    0 non-null      object
 14  Reference               27169 non-null  object
 15  Pr

### Percentage of missing values

In [11]:
pd.pandas.set_option('display.max_rows', None)

In [12]:
sales.isna().mean().round(4) * 100

Code                        0.00
Description                 0.01
Additional Description     99.99
Bar Code                    0.02
Bar Code 2                 94.51
Bar Code 3                 76.40
Serial Number 2            94.51
Serial Number 3            76.40
Department                  0.03
Section                     0.53
Family                     45.03
SubFamily                  68.40
Brand                      99.71
Line                      100.00
Reference                   0.03
Propiedad 1               100.00
Propiedad 2               100.00
Propiedad 3               100.00
Measure                     0.00
UP1                         0.00
UP2                         0.01
UP3                         0.00
UP4                         0.00
UT                         14.11
US1                         0.01
US2                         0.01
US3                         0.00
US4                         0.00
SC?                         0.00
Weight?                     0.00
NumSeries?

#Given a dataframe sales create a copy of the array that is 0 if a field contains a value 
#and 1 for NaN
naInfo = np.zeros(sales.shape)
naInfo[sales.isna().values] = 1
naInfo = pd.DataFrame(naInfo, columns=sales.columns)

fig, ax = plt.subplots()
fig.set_size_inches(13, 9)
ax = sns.heatmap(naInfo, vmin=0, vmax=1, cmap=["white", "#444444"], cbar=False, ax=ax)
ax.set_yticks([])

rect = plt.Rectangle((0, 0), naInfo.shape[1], naInfo.shape[0], linewidth=1, 
                     edgecolor='lightgrey',facecolor='none')
rect = ax.add_patch(rect)
rect.set_clip_on(False)

plt.xticks(rotation=80)
plt.tight_layout()
plt.show()

In [13]:
sales.iloc[0]

Code                                            1
Description               PRESCHOOL FISHERS PRICE
Additional Description                        NaN
Bar Code                             030099499614
Bar Code 2                           030099499621
Bar Code 3                                    NaN
Serial Number 2                      030099499621
Serial Number 3                               NaN
Department                               BOOKSHOP
Section                                     BOOKS
Family                                STORY BOOKS
SubFamily                                     NaN
Brand                                         NaN
Line                                          NaN
Reference                            030099499614
Propiedad 1                                   NaN
Propiedad 2                                   NaN
Propiedad 3                                   NaN
Measure                                        1 
UP1                                             1


In [14]:
per_cent_missing_value_100 = ['Line', 'Propiedad 1', 'Propiedad 2', 'Propiedad 3', 'Manufacturing', 'Purchase Acco.Entry', 'Sale Acco. Entry', 'Purchase Warranty', 'Sale Warranty', 'Picture', 'Season', 'Format', 'Measure 2']

In [15]:
sales['Code'].unique()

array([1, 3, 6, ..., 67609, 67610, nan], dtype=object)

In [16]:
sales['Description'].unique()

array(['PRESCHOOL FISHERS PRICE', 'NOVA NATURAL HOLD HAIR SPRAY 450ML',
       'KINDERGARTEN  FISHERS PRICE', ...,
       'CADBURY DAIRY MILK CCARAMELLO 480ML',
       'GIFTMAKER GIFT BAG BLUE & GOLD YAKGB01X', 'GIZZARD VINE DRESSER'],
      dtype=object)

In [17]:
sales['Charge 1'].unique()

array([0, nan], dtype=object)

In [18]:
sales['Charge 2'].unique()

array([0, nan], dtype=object)

In [37]:
sales['Qty'].nunique()

592

In [38]:
sales['AMOUNT'].nunique()

6028

In [39]:
sales['Cost'].nunique()

4889

In [40]:
sales['% M/S'].nunique()

7703

In [23]:
sales['% M/C'].unique()

array([0, 44, 22.170265660060807, ..., 27.751937984496124,
       14.38076923076923, 40.99410077749194], dtype=object)

In [24]:
sales['Profit'].unique()

array([0, 1320, 12360.3000000001, ..., 3580, 6356.3, 77920805.12561846],
      dtype=object)

In [25]:
sales['Documents Num'].unique()

array([0, 3, 123, 81, 159, 1, 27, 2, 15, 10, 8, 113, 121, 4, 50, 36, 19,
       12, 9, 14, 5, 17, 7, 54, 110, 377, 296, 47, 76, 79, 39, 139, 108,
       41, 18, 28, 6, 29, 11, 43, 16, 22, 13, 20, 69, 51, 82, 131, 25, 74,
       48, 21, 192, 83, 126, 57, 78, 471, 148, 61, 136, 26, 37, 92, 170,
       66, 65, 178, 87, 24, 119, 56, 23, 198, 30, 42, 46, 40, 58, 63, 120,
       94, 68, 33, 52, 430, 34, 44, 100, 640, 546, 2336, 394, 107, 73,
       182, 49, 4400, 7509, 3037, 93, 363, 763, 290, 1373, 3749, 244, 470,
       80, 1045, 71, 444, 199, 206, 607, 1582, 383, 265, 837, 245, 179,
       154, 138, 385, 188, 96, 739, 382, 84, 127, 67, 359, 32, 257, 118,
       140, 102, 70, 31, 172, 999, 177, 185, 282, 365, 314, 886, 168,
       1601, 351, 761, 1371, 248, 62, 64, 98, 180, 35, 906, 181, 77, 536,
       112, 122, 75, 146, 149, 353, 308, 132, 332, 246, 167, 1814, 595,
       1363, 288, 15135, 5101, 3777, 9516, 497, 1544, 3545, 638, 3554,
       582, 4019, 2006, 2437, 4354, 2427, 1391, 2385,

In [26]:
sales['Additional Description'].unique()

array([nan, 'MALTINA PACK OF 6', 'MIXED PASTA'], dtype=object)

In [27]:
sales[sales['Additional Description'] == 'MALTINA PACK OF 6'][['Description', 'Additional Description']]

Description Additional Description
3995  MALTINA CLASSIC 33CL CAN 6PCS      MALTINA PACK OF 6

In [28]:
sales[sales['Additional Description'] == 'MIXED PASTA'][['Description', 'Additional Description']]

Description Additional Description
10245  MIXED PASTA            MIXED PASTA

In [29]:
sales['Department'].unique()

array(['BOOKSHOP', 'TOILETRIES', 'HOUSEHOLD', 'HEALTH & BEAUTY PRODUCTS',
       'BABY PRODUCT', 'GROCERY', 'FRESH FOOD', '3F', 'TOYS',
       'RAW MATERIALS', nan, 'HAMPER', 'ENTERTAINMENT', 'ASSET '],
      dtype=object)

In [30]:
sales['Reference'].unique()

array(['030099499614', '5021156120683', '030099499638', ...,
       '6009198000933', '5012213483605', '608887018974'], dtype=object)

Inestigate measure variable. The values don't seem to make sense

In [31]:
sales['Measure'].value_counts()

1                  27040
1000 GRAMMES         103
1000 milliliter        8
1000 GRAMME            8
1 Qty.                 6
1000 grammes           5
1000 GRAMM             3
1 GRAM                 1
1000 gramme            1
1000 GRAMEES           1
1000 GRAMES            1
Name: Measure, dtype: int64

In [32]:
#what does UP1 mean?
sales['UP1'].value_counts()

1     27176
60        1
Name: UP1, dtype: int64

per_cent_missing_value_100 = ['Line', 'Propiedad 1', 'Propiedad 2', 'Propiedad 3', 'Manufacturing', 'Purchase Acco.Entry', 'Sale Acco. Entry', 'Purchase Warranty', 'Sale Warranty', 'Picture', 'Season', 'Format', 'Measure 2']

'Code', 'Description', 'Additional Description', 'Bar Code',
'Bar Code 2', 'Bar Code 3', 'Serial Number 2', 'Serial Number 3',
'Department', 'Section', 'Family', 'SubFamily', 'Brand', 
'Reference',  'Measure', 'UP1', 'UP2', 'UP3', 'UP4', 'UT ', 
'US1', 'US2', 'US3', 'US4', 'SC?','Weight?', 'NumSeries?', 
'It has Serial Numbers', 'Item Type', 'Unlist', 'Kit items', 'Date LP', 
'Price LP', 'Price', '%Disc LP','Last header discount', 'Last cost', 
'Average Cost', 'Stock cost', 'Date LS', 'Date Modif', 'Type', 'Purchase Tax',
'Sale Tax', 'Currency Code', 'Currency', 'Weight', 'Charge 1',
'Charge 2', 'Qty', 'AMOUNT', 'Cost', '% M/S', '% M/C', 'Profit',
'Documents Num', 'Num. Clients', 'Weight', 'UdMedida2'

For 'Code' do a comparism with another month to see if it is consistent with each SKU

convert_to_dummy = ['Department,'

columns_to_drop = ['Description', 'Bar Code', 'Bar Code 2', 'Bar Code 3', 'Serial Number 2', 'Serial Number 3', 'Section', 'Family', 'SubFamily', 'Brand', 'Reference', 'Measure', 'UP1', 


important_variables_to_sales = ['Department, '

In [33]:
bf = sales['Bar Code'] == sales['Reference']
bf.value_counts()

True     26611
False      567
dtype: int64

In most cases, bar code is usually the same as reference

In [34]:
sales.sample(5)

Code                               Description Additional Description  \
25528  65852                   CROCHET ADULT FACE MASK                    NaN   
13738  50857  LONTOR RECHARGEABLE LED TOUCH CTL-TH300A                    NaN   
26108  66488  SECOND FORM AT MALORY TOWERS EMID BLYTON                    NaN   
19724  59173             PICKWICK STRAWBERRY WAFER 60G                    NaN   
16212  54492   ADS COSMATIC 3D MASCARA WATERPROOF 10ML                    NaN   

            Bar Code Bar Code 2  Bar Code 3 Serial Number 2 Serial Number 3  \
25528         745488        NaN  9999745488             NaN      9999745488   
13738  6939009673158        NaN         NaN             NaN             NaN   
26108  9781444929881        NaN         NaN             NaN             NaN   
19724  8902041017448        NaN         NaN             NaN             NaN   
16212  6950420152398        NaN         NaN             NaN             NaN   

                     Department          Section  ... Qty AMOUNT Cost % M/S  \
25528  HEALTH & BEAUTY PRODUCTS  CLOTHING & SHOE  ...   0      0    0     0   
13738                 HOUSEHOLD   HOME APPLIANCE  ...   0      0    0     0   
26108                  BOOKSHOP            BOOKS  ...   0      0    0     0   
19724                   GROCERY  CONFECTIONARIES  ...   0      0    0     0   
16212  HEALTH & BEAUTY PRODUCTS          MAKE-UP  ...   0      0    0     0   

      % M/C Profit Documents Num Num. Clients Weight UdMedida2  
25528     0      0             0            0      0         0  
13738     0      0             0            0      0         0  
26108     0      0             0            0      0         0  
19724     0      0             0            0      0         0  
16212     0      0             0            0      0         0  

[5 rows x 72 columns]

In [35]:
bool_comp = sales['Price LP'] == sales['Price']

In [36]:
bool_comp.value_counts()

True     24639
False     2539
dtype: int64

Within the timeframe considered, there were 24,597 cases where Price LP was same as Price and 2,535 cases where Price LP wasn't 
same as Price